package interfaces;

/**
 *
 * @author Luriannys Junco
 */
public class companyView extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public companyView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel24 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        companyStorage = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        companyWorkers = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        companyStorage1 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        mainBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setText("$");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jLabel42.setText("UTILIDAD");
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("ALMACÉN");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        jLabel41.setText("$");
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("TRABAJADORES");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, -1));

        jLabel40.setText("COSTOS");
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        jLabel23.setText("GANANCIAS");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel27.setText("companyName");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel43.setText("$");
        getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));

        companyStorage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Project Manager");
        companyStorage.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel7.setText("0/0");
        companyStorage.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel8.setText("Faltas");
        companyStorage.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, -1, -1));

        jLabel19.setText("0/0");
        companyStorage.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 55, -1, -1));

        jLabel9.setText("Director");
        companyStorage.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 125, -1, -1));

        jLabel20.setText("0/0");
        companyStorage.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        jLabel22.setText("0/0");
        companyStorage.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 125, -1, -1));

        jLabel25.setText("DÍAS DE ENTREGA");
        companyStorage.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 195, -1, -1));

        jLabel26.setText("0/0");
        companyStorage.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 195, -1, -1));

        jLabel13.setText("Dinero descontado");
        companyStorage.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        getContentPane().add(companyStorage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 170, 230));

        companyWorkers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Placa");
        companyWorkers.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-menos-30.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton1.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton1.setPreferredSize(new java.awt.Dimension(25, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        companyWorkers.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 15, -1, -1));
        jButton1.getAccessibleContext().setAccessibleDescription("");

        jLabel4.setText("0");
        companyWorkers.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-más-30.png"))); // NOI18N
        jButton6.setBorderPainted(false);
        jButton6.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton6.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton6.setPreferredSize(new java.awt.Dimension(25, 25));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        companyWorkers.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 15, -1, -1));

        jLabel2.setText("CPU");
        companyWorkers.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-menos-30.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton2.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton2.setPreferredSize(new java.awt.Dimension(25, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        companyWorkers.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        jLabel11.setText("0");
        companyWorkers.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 55, -1, -1));

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-más-30.png"))); // NOI18N
        jButton13.setBorderPainted(false);
        jButton13.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton13.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton13.setPreferredSize(new java.awt.Dimension(25, 25));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        companyWorkers.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        jLabel3.setText("Fuente de poder");
        companyWorkers.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 125, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-menos-30.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton3.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton3.setPreferredSize(new java.awt.Dimension(25, 25));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        companyWorkers.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 85, -1, -1));

        jLabel12.setText("0");
        companyWorkers.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-más-30.png"))); // NOI18N
        jButton14.setBorderPainted(false);
        jButton14.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton14.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton14.setPreferredSize(new java.awt.Dimension(25, 25));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        companyWorkers.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 85, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-menos-30.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton4.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton4.setPreferredSize(new java.awt.Dimension(25, 25));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        companyWorkers.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        jLabel14.setText("0");
        companyWorkers.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 125, -1, -1));

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-más-30.png"))); // NOI18N
        jButton15.setBorderPainted(false);
        jButton15.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton15.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton15.setPreferredSize(new java.awt.Dimension(25, 25));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        companyWorkers.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        jLabel15.setText("Tarjeta gráfica");
        companyWorkers.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-menos-30.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton5.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton5.setPreferredSize(new java.awt.Dimension(25, 25));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        companyWorkers.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 155, -1, -1));

        jLabel16.setText("0");
        companyWorkers.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-más-30.png"))); // NOI18N
        jButton16.setBorderPainted(false);
        jButton16.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton16.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton16.setPreferredSize(new java.awt.Dimension(25, 25));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        companyWorkers.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 155, -1, -1));

        jLabel17.setText("Ensambladores");
        companyWorkers.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 195, -1, -1));

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-menos-30.png"))); // NOI18N
        jButton17.setBorderPainted(false);
        jButton17.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton17.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton17.setPreferredSize(new java.awt.Dimension(25, 25));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        companyWorkers.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        jLabel18.setText("0");
        companyWorkers.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 195, -1, -1));

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-más-30.png"))); // NOI18N
        jButton18.setBorderPainted(false);
        jButton18.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton18.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton18.setPreferredSize(new java.awt.Dimension(25, 25));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        companyWorkers.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        jLabel10.setText("RAM");
        companyWorkers.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        getContentPane().add(companyWorkers, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 240, 230));

        companyStorage1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setText("Placa");
        companyStorage1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel29.setText("0/0");
        companyStorage1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel30.setText("CPU");
        companyStorage1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, -1, -1));

        jLabel31.setText("0/0");
        companyStorage1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 55, -1, -1));

        jLabel32.setText("Fuente de poder");
        companyStorage1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 125, -1, -1));

        jLabel33.setText("0/0");
        companyStorage1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        jLabel34.setText("0/0");
        companyStorage1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 125, -1, -1));

        jLabel35.setText("Tarjeta gráfica");
        companyStorage1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel36.setText("0/0");
        companyStorage1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jLabel37.setText("Ensambladores");
        companyStorage1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 195, -1, -1));

        jLabel38.setText("0/0");
        companyStorage1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 195, -1, -1));

        jLabel39.setText("RAM");
        companyStorage1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        getContentPane().add(companyStorage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 170, 230));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 111, -1, -1));

        mainBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nasa-Q1p7bh3SHj8-unsplash.jpg"))); // NOI18N
        mainBackground.setText("jLabel1");
        mainBackground.setMaximumSize(new java.awt.Dimension(680, 425));
        mainBackground.setMinimumSize(new java.awt.Dimension(680, 425));
        mainBackground.setPreferredSize(new java.awt.Dimension(680, 425));
        getContentPane().add(mainBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(companyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(companyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(companyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(companyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new companyView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel companyStorage;
    private javax.swing.JPanel companyStorage1;
    private javax.swing.JPanel companyWorkers;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mainBackground;
    // End of variables declaration//GEN-END:variables
}
