package interfaces;

/**
 *
 * @author Luriannys Junco
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dellButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        hpButton = new javax.swing.JButton();
        mainTitle = new javax.swing.JLabel();
        mainBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(640, 425));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 111, -1, -1));

        dellButton.setBackground(new java.awt.Color(102, 102, 102));
        dellButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dell_logo_icon_167699 (2).png"))); // NOI18N
        dellButton.setText("DELL");
        dellButton.setBorderPainted(false);
        dellButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dellButtonActionPerformed(evt);
            }
        });
        getContentPane().add(dellButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 140, 50));

        settingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/settingstoolswheel-115840_115789.png"))); // NOI18N
        settingsButton.setBorderPainted(false);
        getContentPane().add(settingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, -1, -1));

        hpButton.setBackground(new java.awt.Color(102, 102, 102));
        hpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hplogo_94383 (6).png"))); // NOI18N
        hpButton.setText("HP");
        hpButton.setBorderPainted(false);
        hpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hpButtonActionPerformed(evt);
            }
        });
        getContentPane().add(hpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 140, 50));

        mainTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        mainTitle.setForeground(new java.awt.Color(255, 255, 255));
        mainTitle.setText("HP VS DELL");
        getContentPane().add(mainTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        mainBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nasa-Q1p7bh3SHj8-unsplash.jpg"))); // NOI18N
        mainBackground.setText("jLabel1");
        mainBackground.setMaximumSize(new java.awt.Dimension(680, 425));
        mainBackground.setMinimumSize(new java.awt.Dimension(680, 425));
        mainBackground.setPreferredSize(new java.awt.Dimension(680, 425));
        getContentPane().add(mainBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hpButtonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_hpButtonActionPerformed

    private void dellButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dellButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dellButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dellButton;
    private javax.swing.JButton hpButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mainBackground;
    private javax.swing.JLabel mainTitle;
    private javax.swing.JButton settingsButton;
    // End of variables declaration//GEN-END:variables
}
